FROM nginx

WORKDIR /home
LABEL autor=monroebu

COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./server.c .
COPY ./run.sh .

RUN apt-get update \
    && apt-get install -y gcc spawn-fcgi libfcgi-dev \    
    && gcc -o server server.c -lfcgi
ENTRYPOINT [ "./run.sh" ]